### ISSUE TITLE
Build test

### ISSUE THREAD

**Issue by albert21martins** [diegoeck/px4tuning#1]
Hi I was trying to build your code to see if I can get good output for the Px4 PID controller. Running ./px4att.py log_0_2018-8-18-10-38-54.ulg
Sampling rate: 234.17198324717756 Hz

=== ROLL RATE
Custo:  1.9271846749798132
Old PID(s): 0.19699999690055847 0.9409999847412109 0.0
Traceback (most recent call last):
  File "./px4att.py", line 202, in <module>
    main()
  File "./px4att.py", line 67, in main
    rho_vrft=vrft.vrft_pid_mf(D.u_r, D.y_r_r, a0, b0, 'loco'  ,P,0.98)
  File "/usr/lib/python3.7/site-packages/px4tuning-0.1-py3.7.egg/px4tuning/vrft.py", line 173, in vrft_pid_mf
    rho = la.solve(R, S)
  File "/usr/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 403, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
TypeError: No loop matching the specified signature and casting
was found for ufunc solve1

Do you know what I am missing?

thanks in advance

**Comment by diegoeck** [comment]
It seems you have some problem with Numpy library.
I'm not sure how to help...

**Comment by albert21martins** [comment]
Yes, sorry I forgot to reply. It was some dependencies missing from my part. Thanks for the answer anyway
