### ISSUE TITLE
Article about Virtual Reference Feedback Tuning method

### ISSUE THREAD

**Issue by frontw** [diegoeck/px4tuning#3]
Hi! 

Thanks for this repo!

Could you, please, recommend some article to get familiar with Virtual Reference Feedback Tuning method and its application for multirotor.

Thanks!

**Comment by diegoeck** [comment]
For data-driven control techniques, including VRFT I recommend our book:
http://dx.doi.org/10.1007/978-94-007-2300-9

And for articles our webpage/publications:
www.datadrivencontrol.com

This is a thesis (not mine):
https://www.politesi.polimi.it/bitstream/10589/137027/1/thesis.pdf

This is an article (mine) of other data-driven methods used with quadcopters:
http://www.datadrivencontrol.com/wp-content/papercite-data/pdf/tesch-eckhard-guarienti-2016.pdf

This is an article about VRFT and quadcopters [in portuguese]:
http://dx.doi.org/10.5540/03.2016.004.01.0092

**Comment by frontw** [comment]
Thanks! I see, there is big background for this repo.
Maybe, it would be useful to put these links to readme?
